// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "fe670ad6-3d14-45b3-b45c-a865c9859d9a");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1774029836);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1774029835);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1774029835);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "d874d023-3a3b-4b14-a971-5af04ef19018");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1774029834);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1774029834);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 163);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v4:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.discoverystream.merino-provider.ohttp.enabled", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs", "newtab_stories_1, newtab_stories_2, newtab_stories_3, newtab_stories_4, newtab_stories_5, newtab_stories_6, newtab_billboard");
user_pref("browser.newtabpage.activity-stream.discoverystream.placements.spocs.counts", "1, 1, 1, 1, 1, 1, 1");
user_pref("browser.newtabpage.activity-stream.discoverystream.promoCard.enabled", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.customizeMenuPanel.enabled", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.interestPicker.visibleSections", "top_stories_section,arts,education-science,nfl,government,explained,photojournalism,in-conversation,headlines,in-the-zeitgeist,featured-videos,health,business,downtime,connections,small-wins,education,sports,marchmadness,music");
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.personalization.enabled", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d9f46872-6eb8-435f-a125-7b71919a0c7b}");
user_pref("browser.newtabpage.activity-stream.newtabAdSize.billboard", true);
user_pref("browser.newtabpage.activity-stream.newtabAdSize.billboard.position", "1");
user_pref("browser.newtabpage.activity-stream.telemetry.surfaceId", "NEW_TAB_EN_US");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "150.1.20260304.231049");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.profiles.enabled", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1774029834);
user_pref("browser.safebrowsing.provider.google5.lastupdatetime", "1774029843216");
user_pref("browser.safebrowsing.provider.google5.nextupdatetime", "1774116243216");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1774029836604");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1774051436604");
user_pref("browser.search.region", "US");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1774029834");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260310125956");
user_pref("browser.startup.homepage_override.mstone", "148.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1774029835);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1774029835);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 6);
user_pref("captchadetection.lastSubmission", 1774029);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "791401da-2d12-4bdf-8631-8569ae94eb6e");
user_pref("datareporting.dau.cachedUsageProfileID", "d31f588a-91d1-496f-94ad-e0a8087e2e03");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1774029834887");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "148.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "72a625806ce94c6ba41f972835e56c39");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260310125956");
user_pref("extensions.lastAppVersion", "148.0.2");
user_pref("extensions.lastPlatformVersion", "148.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_interventions", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"e031919a-2a28-40c6-9e96-8abbd25bdafc\",\"formautofill@mozilla.org\":\"5ca9ea32-1070-448b-95d0-32d0e6c4e78d\",\"ipp-activator@mozilla.com\":\"6a0f8ac9-137b-492b-b557-74847e4def77\",\"pictureinpicture@mozilla.org\":\"2561ef43-4146-4c39-afad-6cca064b756e\",\"addons-search-detection@mozilla.com\":\"51fa2e2f-056f-48fb-ae22-19e9bd600d32\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"2aa0b909-e420-4400-9eb4-61e665acb04c\",\"default-theme@mozilla.org\":\"72e70881-07c9-409d-b8f6-95446c5b5ba1\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "7289031c-1656-4b46-91ad-834ccc0369f6");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("toolkit.profiles.storeID", "1705465d");
user_pref("toolkit.telemetry.cachedClientID", "4a180396-204e-4768-82b6-d0e8a8aa10a6");
user_pref("toolkit.telemetry.cachedProfileGroupID", "81db5ad1-179c-466c-a2d2-b3b321ac5caa");
user_pref("toolkit.telemetry.previousBuildID", "20260310125956");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
